// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoxgrwtemavpoqqywiov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVveGdyd3RlbWF2cG9xcXl3aW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODI1ODYsImV4cCI6MjA3MjY1ODU4Nn0.a4k04EptuNz7-PqWtxD63-PP8y8VpQ8PUeFPZZz2TJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});